# $HOME/.config/alacritty/alacritty.toml
# by Jerrod Havig 2024-06-06
#
#

import = [
	"~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
]

[ env ]

TERM = "xterm-256color"

[ window ]

opacity = 0.9

padding.x = 6
padding.y = 3

[ font ]

normal.family = "GeistMonoNerdFont"
bold.family = "GeistMonoNerdFont"
italic.family = "GeistMonoNerdFont"
bold_italic.family = "GeistMonoNerdFont"

size = 8

[ cursor ]

unfocused_hollow = true

[ scrolling ]

history = 2000
